### ISSUE TITLE
Visualisation of courses as teacher

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#32]
### Description

As a teacher 
I want to access to my courses
So that I can find my subjects gathered by courses

### Acceptance tests
>GIVEN

An authenticated teacher 
>WHEN

He clicks on the "my recent subjects" button on the left side bar
>THEN

An interface on the screen allows him to see all of his recent subjects

---
> GIVEN

An authenticated teacher 
>WHEN

He clicks on the "my shared subjects" button on the left side bar
>THEN

An interface on the screen allows him to see all of his shared subjects

---

>GIVEN

An authenticated teacher 
>WHEN

He clicks on the "his courses " button on the left side bar
>THEN

An interface on the screen allows him to see all of his courses 
>AND

He clicks on a course of the courses interface
>THEN

Another interface on the screen allows him to see all the subject ordered alphabetically linked to course selected

### Tasks

- [ ] Finaliser la maquette avec attention particulière sur la barre de bouton à gauche et le volet central
- [ ] Le développement des vues
- [ ] Le développement du modèle (schéma de la base ?, la classe du domaine?, les relations dans les classes du domaine?, le service de gestion du sujet avec finder adapté)
- [ ] Le développement du contrôleur

**Comment by FranckSilvestre** [comment]
I think the home page of the teacher is the page that displays the courses list.
I think it would be cool to have a two-views screen displaying in the left panel the list of courses and in the right panel, the list of subjects for the selected course.
The left panel could displays a "virtual" group of subjects corresponding to the recently used subjects. This virtual group would be the default selected group.
