### ISSUE TITLE
Modification of an assignment

### ISSUE THREAD

**Issue by FranckSilvestre** [elaastic/elaastic-questions-server#43]
### Description

As a teacher
I want to modify properties of an assignment
So that I can take into account the needs for change of properties of an assignment

### Tasks
- [ ] Controller (update action)
- [ ] Update view if necessary
- [ ] model: update operation on assignment
